'use strict';
// Initial schema migration for Nexus -- generated by consolidating and
// redistributing the original per-database migrations (kongsberg/
// production/logistics/production_archive, 2026-08-04) per the approved
// restructure plan. Every statement is extracted programmatically from the
// original migration files (not retyped), only schema-qualified table
// prefixes are rewritten where a table changed database/schema.

/** @param {import('knex').Knex} knex */
exports.up = async function (knex) {
    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.NotificationDeliveries') AND type = 'U')\r\nCREATE TABLE dbo.NotificationDeliveries (\r\n    DeliveryID INT IDENTITY(1,1) NOT NULL\r\n,    NotificationID INT NOT NULL\r\n,    UserID INT NOT NULL\r\n,    IsRead BIT NOT NULL\r\n,    IsDismissed BIT NOT NULL\r\n,    ReadAt DATETIME NULL\r\n,    DismissedAt DATETIME NULL\r\n,\r\n    CONSTRAINT PK_NotificationDeliveries PRIMARY KEY (DeliveryID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Notifications') AND type = 'U')\r\nCREATE TABLE dbo.Notifications (\r\n    NotificationID INT IDENTITY(1,1) NOT NULL\r\n,    Title NVARCHAR(120) NOT NULL\r\n,    Body NVARCHAR(MAX) NOT NULL\r\n,    Severity TINYINT NOT NULL\r\n,    Category NVARCHAR(50) NULL\r\n,    ActionLabel NVARCHAR(60) NULL\r\n,    ActionURL NVARCHAR(500) NULL\r\n,    TargetType NVARCHAR(20) NULL\r\n,    TargetValue NVARCHAR(100) NULL\r\n,    CreatedByUserID INT NULL\r\n,    CreatedAt DATETIME NOT NULL\r\n,    ExpiresAt DATETIME NULL\r\n,\r\n    CONSTRAINT PK_Notifications PRIMARY KEY (NotificationID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalAuditLog') AND type = 'U')\r\nCREATE TABLE dbo.PortalAuditLog (\r\n    LogID INT IDENTITY(1,1) NOT NULL\r\n,    EventTime DATETIME NOT NULL\r\n,    Username NVARCHAR(80) NULL\r\n,    EventType NVARCHAR(50) NOT NULL\r\n,    Detail NVARCHAR(500) NULL\r\n,    IPAddress NVARCHAR(45) NULL\r\n,\r\n    CONSTRAINT PK__PortalAuditLog__59C55456 PRIMARY KEY (LogID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalPermissions') AND type = 'U')\r\nCREATE TABLE dbo.PortalPermissions (\r\n    PermissionCode NVARCHAR(50) NOT NULL\r\n,    PermissionName NVARCHAR(100) NOT NULL\r\n,    Description NVARCHAR(500) NULL\r\n,    Category NVARCHAR(50) NOT NULL\r\n,    CreatedAt DATETIME NOT NULL\r\n,\r\n    CONSTRAINT PK_PortalPermissions PRIMARY KEY (PermissionCode)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalSessions') AND type = 'U')\r\nCREATE TABLE dbo.PortalSessions (\r\n    SessionID NVARCHAR(128) NOT NULL\r\n,    SessionData NVARCHAR(MAX) NOT NULL\r\n,    ExpiresUtc DATETIME NOT NULL\r\n,    CreatedUtc DATETIME NOT NULL\r\n,    UpdatedUtc DATETIME NOT NULL\r\n,\r\n    CONSTRAINT PK_PortalSessions PRIMARY KEY (SessionID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUserDepartments') AND type = 'U')\r\nCREATE TABLE dbo.PortalUserDepartments (\r\n    ID INT IDENTITY(1,1) NOT NULL\r\n,    UserID INT NOT NULL\r\n,    Department NVARCHAR(50) NOT NULL\r\n,    GrantedBy NVARCHAR(80) NULL\r\n,    GrantedAt DATETIME NOT NULL\r\n,\r\n    CONSTRAINT PK__PortalUserDepart__55009F39 PRIMARY KEY (ID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUserPermissions') AND type = 'U')\r\nCREATE TABLE dbo.PortalUserPermissions (\r\n    UserPermissionID INT IDENTITY(1,1) NOT NULL\r\n,    UserID INT NOT NULL\r\n,    PermissionCode NVARCHAR(50) NOT NULL\r\n,    GrantedAt DATETIME NOT NULL\r\n,    GrantedByUserID INT NULL\r\n,\r\n    CONSTRAINT PK_PortalUserPermissions PRIMARY KEY (UserPermissionID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUsers') AND type = 'U')\r\nCREATE TABLE dbo.PortalUsers (\r\n    UserID INT IDENTITY(1,1) NOT NULL\r\n,    Username NVARCHAR(80) NOT NULL\r\n,    Email NVARCHAR(160) NOT NULL\r\n,    PasswordHash NVARCHAR(256) NOT NULL\r\n,    Role NVARCHAR(20) NOT NULL\r\n,    IsActive BIT NOT NULL\r\n,    IsLocked BIT NOT NULL\r\n,    FailedLogins INT NOT NULL\r\n,    CreatedAt DATETIME NOT NULL\r\n,    LastLogin DATETIME NULL\r\n,    ApprovedBy NVARCHAR(80) NULL\r\n,    ApprovedAt DATETIME NULL\r\n,    Notes NVARCHAR(500) NULL\r\n,    FirstName NVARCHAR(80) NULL\r\n,    LastName NVARCHAR(80) NULL\r\n,    DefaultPrinterID NVARCHAR(50) NULL\r\n,    ShortIdleTimeout BIT NOT NULL\r\n,    reset_token VARCHAR(255) NULL\r\n,    reset_token_expires DATETIME NULL\r\n,    SapUsername NVARCHAR(40) NULL\r\n,    SapPasswordEncrypted NVARCHAR(400) NULL\r\n,    SapCredentialUpdatedAt DATETIME NULL\r\n,\r\n    CONSTRAINT PK__PortalUsers__4D5F7D71 PRIMARY KEY (UserID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.RefreshLog') AND type = 'U')\r\nCREATE TABLE dbo.RefreshLog (\r\n    RunId INT IDENTITY(1,1) NOT NULL\r\n,    DatasetName VARCHAR(50) NOT NULL\r\n,    StartedAtUtc DATETIME NOT NULL\r\n,    CompletedAtUtc DATETIME NULL\r\n,    TotalRows INT NULL\r\n,    Status VARCHAR(20) NOT NULL\r\n,    ErrorMessage VARCHAR(4000) NULL\r\n,\r\n    CONSTRAINT PK__RefreshLog__7EF6D905 PRIMARY KEY (RunId)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ScheduledDeployments') AND type = 'U')\r\nCREATE TABLE dbo.ScheduledDeployments (\r\n    DeploymentID INT IDENTITY(1,1) NOT NULL\r\n,    ScheduledAt DATETIME NOT NULL\r\n,    GitRef NVARCHAR(100) NOT NULL\r\n,    WarningMinutes INT NOT NULL\r\n,    Status NVARCHAR(20) NOT NULL\r\n,    Notes NVARCHAR(500) NULL\r\n,    CreatedByUserID INT NULL\r\n,    CreatedByUsername NVARCHAR(80) NULL\r\n,    CreatedAt DATETIME NOT NULL\r\n,    StartedAt DATETIME NULL\r\n,    CompletedAt DATETIME NULL\r\n,    OutputLog NVARCHAR(MAX) NULL\r\n,    ErrorMessage NVARCHAR(MAX) NULL\r\n,    CancelledAt DATETIME NULL\r\n,    CancelledBy NVARCHAR(80) NULL\r\n,\r\n    CONSTRAINT PK_ScheduledDeployments PRIMARY KEY (DeploymentID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.sysdiagrams') AND type = 'U')\r\nCREATE TABLE dbo.sysdiagrams (\r\n    name SYSNAME NOT NULL\r\n,    principal_id INT NOT NULL\r\n,    diagram_id INT IDENTITY(1,1) NOT NULL\r\n,    version INT NULL\r\n,    definition VARBINARY(MAX) NULL\r\n,\r\n    CONSTRAINT PK__sysdiagrams__7E6CC920 PRIMARY KEY (diagram_id)\r\n)");

    await knex.raw("ALTER TABLE dbo.NotificationDeliveries ADD CONSTRAINT DF__Notificat__IsRea__7A3223E8 DEFAULT ((0)) FOR IsRead");

    await knex.raw("ALTER TABLE dbo.NotificationDeliveries ADD CONSTRAINT DF__Notificat__IsDis__7B264821 DEFAULT ((0)) FOR IsDismissed");

    await knex.raw("ALTER TABLE dbo.Notifications ADD CONSTRAINT DF__Notificat__Sever__756D6ECB DEFAULT ((1)) FOR Severity");

    await knex.raw("ALTER TABLE dbo.Notifications ADD CONSTRAINT DF__Notificat__Creat__76619304 DEFAULT (getdate()) FOR CreatedAt");

    await knex.raw("ALTER TABLE dbo.PortalAuditLog ADD CONSTRAINT DF__PortalAud__Event__5AB9788F DEFAULT (getdate()) FOR EventTime");

    await knex.raw("ALTER TABLE dbo.PortalPermissions ADD CONSTRAINT DF__PortalPer__Categ__6166761E DEFAULT (N'General') FOR Category");

    await knex.raw("ALTER TABLE dbo.PortalPermissions ADD CONSTRAINT DF__PortalPer__Creat__625A9A57 DEFAULT (getdate()) FOR CreatedAt");

    await knex.raw("ALTER TABLE dbo.PortalSessions ADD CONSTRAINT DF__PortalSes__Creat__51EF2864 DEFAULT (getutcdate()) FOR CreatedUtc");

    await knex.raw("ALTER TABLE dbo.PortalSessions ADD CONSTRAINT DF__PortalSes__Updat__52E34C9D DEFAULT (getutcdate()) FOR UpdatedUtc");

    await knex.raw("ALTER TABLE dbo.PortalUserDepartments ADD CONSTRAINT DF__PortalUse__Grant__57DD0BE4 DEFAULT (getdate()) FOR GrantedAt");

    await knex.raw("ALTER TABLE dbo.PortalUserPermissions ADD CONSTRAINT DF__PortalUse__Grant__662B2B3B DEFAULT (getdate()) FOR GrantedAt");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUser__Role__4E53A1AA DEFAULT ('viewer') FOR Role");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUse__IsAct__503BEA1C DEFAULT ((0)) FOR IsActive");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUse__IsLoc__51300E55 DEFAULT ((0)) FOR IsLocked");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUse__Faile__5224328E DEFAULT ((0)) FOR FailedLogins");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUse__Creat__531856C7 DEFAULT (getdate()) FOR CreatedAt");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT DF__PortalUse__Short__5E54FF49 DEFAULT ((0)) FOR ShortIdleTimeout");

    await knex.raw("ALTER TABLE dbo.ScheduledDeployments ADD CONSTRAINT DF__Scheduled__GitRe__1C873BEC DEFAULT ('main') FOR GitRef");

    await knex.raw("ALTER TABLE dbo.ScheduledDeployments ADD CONSTRAINT DF__Scheduled__Warni__1D7B6025 DEFAULT ((15)) FOR WarningMinutes");

    await knex.raw("ALTER TABLE dbo.ScheduledDeployments ADD CONSTRAINT DF__Scheduled__Statu__1E6F845E DEFAULT ('pending') FOR Status");

    await knex.raw("ALTER TABLE dbo.ScheduledDeployments ADD CONSTRAINT DF__Scheduled__Creat__1F63A897 DEFAULT (getdate()) FOR CreatedAt");

    await knex.raw("ALTER TABLE dbo.NotificationDeliveries ADD CONSTRAINT UQ_Delivery_User UNIQUE (NotificationID, UserID)");

    await knex.raw("ALTER TABLE dbo.PortalUserPermissions ADD CONSTRAINT UQ_UserPermission UNIQUE (UserID, PermissionCode)");

    await knex.raw("ALTER TABLE dbo.sysdiagrams ADD CONSTRAINT UK_principal_name UNIQUE (principal_id, name)");

    await knex.raw("ALTER TABLE dbo.PortalUserDepartments ADD CONSTRAINT CK__PortalUse__Depar__56E8E7AB CHECK ([Department]='management' OR [Department]='engineering' OR [Department]='quality' OR [Department]='sales' OR [Department]='finance' OR [Department]='warehouse' OR [Department]='logistics' OR [Department]='production')");

    await knex.raw("ALTER TABLE dbo.PortalUsers ADD CONSTRAINT CK_PortalUsers_Role CHECK ([Role]=N'superadmin' OR [Role]=N'admin' OR [Role]=N'operator')");

    await knex.raw("CREATE NONCLUSTERED INDEX IX_Deliveries_NotifID ON dbo.NotificationDeliveries (NotificationID)");

    await knex.raw("CREATE NONCLUSTERED INDEX IX_Deliveries_User ON dbo.NotificationDeliveries (UserID, IsDismissed, IsRead)");

    await knex.raw("CREATE NONCLUSTERED INDEX IX_PortalSessions_Expires ON dbo.PortalSessions (ExpiresUtc)");

    await knex.raw("CREATE UNIQUE NONCLUSTERED INDEX UX_UserDept ON dbo.PortalUserDepartments (UserID, Department)");

    await knex.raw("CREATE NONCLUSTERED INDEX IX_UserPerms_UserID ON dbo.PortalUserPermissions (UserID)");

    await knex.raw("CREATE UNIQUE NONCLUSTERED INDEX UX_PortalUsers_Email ON dbo.PortalUsers (Email)");

    await knex.raw("CREATE UNIQUE NONCLUSTERED INDEX UX_PortalUsers_Username ON dbo.PortalUsers (Username)");

    await knex.raw("CREATE NONCLUSTERED INDEX IX_ScheduledDeployments_DueCheck ON dbo.ScheduledDeployments (Status, ScheduledAt)");

    await knex.raw("ALTER TABLE dbo.NotificationDeliveries ADD CONSTRAINT FK_Deliveries_Notification FOREIGN KEY (NotificationID) REFERENCES dbo.Notifications (NotificationID) ON DELETE CASCADE");

    await knex.raw("ALTER TABLE dbo.NotificationDeliveries ADD CONSTRAINT FK_Deliveries_User FOREIGN KEY (UserID) REFERENCES dbo.PortalUsers (UserID)");

    await knex.raw("ALTER TABLE dbo.PortalUserDepartments ADD CONSTRAINT FK__PortalUse__UserI__55F4C372 FOREIGN KEY (UserID) REFERENCES dbo.PortalUsers (UserID) ON DELETE CASCADE");

    await knex.raw("ALTER TABLE dbo.PortalUserPermissions ADD CONSTRAINT FK_UserPerms_Perm FOREIGN KEY (PermissionCode) REFERENCES dbo.PortalPermissions (PermissionCode)");

    await knex.raw("ALTER TABLE dbo.PortalUserPermissions ADD CONSTRAINT FK_UserPerms_User FOREIGN KEY (UserID) REFERENCES dbo.PortalUsers (UserID)");
};

/** @param {import('knex').Knex} knex */
exports.down = async function (knex) {
    await knex.raw('ALTER TABLE dbo.NotificationDeliveries DROP CONSTRAINT FK_Deliveries_Notification');
    await knex.raw('ALTER TABLE dbo.NotificationDeliveries DROP CONSTRAINT FK_Deliveries_User');
    await knex.raw('ALTER TABLE dbo.PortalUserDepartments DROP CONSTRAINT FK__PortalUse__UserI__55F4C372');
    await knex.raw('ALTER TABLE dbo.PortalUserPermissions DROP CONSTRAINT FK_UserPerms_Perm');
    await knex.raw('ALTER TABLE dbo.PortalUserPermissions DROP CONSTRAINT FK_UserPerms_User');

    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.NotificationDeliveries') AND type = 'U') DROP TABLE dbo.NotificationDeliveries");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Notifications') AND type = 'U') DROP TABLE dbo.Notifications");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalAuditLog') AND type = 'U') DROP TABLE dbo.PortalAuditLog");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalPermissions') AND type = 'U') DROP TABLE dbo.PortalPermissions");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalSessions') AND type = 'U') DROP TABLE dbo.PortalSessions");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUserDepartments') AND type = 'U') DROP TABLE dbo.PortalUserDepartments");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUserPermissions') AND type = 'U') DROP TABLE dbo.PortalUserPermissions");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.PortalUsers') AND type = 'U') DROP TABLE dbo.PortalUsers");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.RefreshLog') AND type = 'U') DROP TABLE dbo.RefreshLog");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ScheduledDeployments') AND type = 'U') DROP TABLE dbo.ScheduledDeployments");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.sysdiagrams') AND type = 'U') DROP TABLE dbo.sysdiagrams");

};
