'use strict';
// Initial schema migration for NexusArchive -- generated by consolidating and
// redistributing the original per-database migrations (kongsberg/
// production/logistics/production_archive, 2026-08-04) per the approved
// restructure plan. Every statement is extracted programmatically from the
// original migration files (not retyped), only schema-qualified table
// prefixes are rewritten where a table changed database/schema.

/** @param {import('knex').Knex} knex */
exports.up = async function (knex) {
    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.archive') AND type = 'U')\r\nCREATE TABLE dbo.archive (\r\n    Area VARCHAR(50) NOT NULL\r\n,    Batch VARCHAR(50) NOT NULL\r\n,    BatchID INT NOT NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    Operator VARCHAR(50) NOT NULL\r\n,    Customer VARCHAR(50) NULL\r\n,    TotalLength FLOAT NOT NULL\r\n,    Shift NVARCHAR(10) NOT NULL\r\n,    Test NVARCHAR(10) NOT NULL\r\n,    DrumWeight NCHAR(10) NULL\r\n,    CreationDate VARCHAR(50) NOT NULL\r\n,    Drum NVARCHAR(8) NOT NULL\r\n,    SAP NVARCHAR(10) NULL\r\n,    Mat_IN NVARCHAR(10) NULL\r\n,    Mat_OUT NVARCHAR(10) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Batches') AND type = 'U')\r\nCREATE TABLE dbo.Batches (\r\n    Area VARCHAR(50) NOT NULL\r\n,    Batch NVARCHAR(100) NULL\r\n,    BatchID INT NOT NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    Operator NVARCHAR(50) NOT NULL\r\n,    Customer NVARCHAR(50) NULL\r\n,    TotalLength FLOAT NOT NULL\r\n,    Shift NVARCHAR(10) NOT NULL\r\n,    Test NVARCHAR(10) NOT NULL\r\n,    DrumWeight FLOAT NULL\r\n,    CreationDate NVARCHAR(50) NOT NULL\r\n,    Drum NVARCHAR(8) NOT NULL\r\n,    SAP NVARCHAR(10) NULL\r\n,    Mat_IN NVARCHAR(10) NULL\r\n,    Mat_OUT NVARCHAR(10) NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n,\r\n    CONSTRAINT PK_Batches PRIMARY KEY (BatchID)\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Coils') AND type = 'U')\r\nCREATE TABLE dbo.Coils (\r\n    Batch NVARCHAR(20) NOT NULL\r\n,    Coil FLOAT NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Convo') AND type = 'U')\r\nCREATE TABLE dbo.Convo (\r\n    ConvoID NVARCHAR(10) NOT NULL\r\n,    RunDate NVARCHAR(10) NOT NULL\r\n,    StartTime NVARCHAR(5) NOT NULL\r\n,    StopTime NVARCHAR(5) NOT NULL\r\n,    Operator NVARCHAR(10) NOT NULL\r\n,    Machine NVARCHAR(2) NOT NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    Meters FLOAT NOT NULL\r\n,    InspectionDate NVARCHAR(10) NULL\r\n,    MaterialDocument NVARCHAR(10) NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoMessages') AND type = 'U')\r\nCREATE TABLE dbo.ConvoMessages (\r\n    Batch NVARCHAR(10) NOT NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoTrace') AND type = 'U')\r\nCREATE TABLE dbo.ConvoTrace (\r\n    ConvoID NVARCHAR(10) NOT NULL\r\n,    MatDoc NVARCHAR(10) NOT NULL\r\n,    Component NVARCHAR(18) NOT NULL\r\n,    Batch NVARCHAR(18) NOT NULL\r\n,    CompLength NVARCHAR(50) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoWaste') AND type = 'U')\r\nCREATE TABLE dbo.ConvoWaste (\r\n    convobatch NVARCHAR(10) NOT NULL\r\n,    reason NVARCHAR(4) NOT NULL\r\n,    entered_weight NVARCHAR(50) NOT NULL\r\n,    calc_comp_length NVARCHAR(50) NOT NULL\r\n,    calc_assy_length NVARCHAR(50) NOT NULL\r\n,    kgpm_used NVARCHAR(50) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Emails') AND type = 'U')\r\nCREATE TABLE dbo.Emails (\r\n    ID BIGINT NOT NULL\r\n,    address NVARCHAR(100) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Ewald') AND type = 'U')\r\nCREATE TABLE dbo.Ewald (\r\n    ID NVARCHAR(10) NOT NULL\r\n,    Drum NVARCHAR(10) NOT NULL\r\n,    CreationDate NVARCHAR(50) NOT NULL\r\n,    CreationTime NVARCHAR(50) NOT NULL\r\n,    Shift NVARCHAR(10) NOT NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    TotalQty INT NOT NULL\r\n,    BoxCount INT NOT NULL\r\n,    Firewall BIT NOT NULL\r\n,    Operator NVARCHAR(50) NOT NULL\r\n,    Machine NVARCHAR(2) NOT NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldBoxes') AND type = 'U')\r\nCREATE TABLE dbo.EwaldBoxes (\r\n    EwaldID NVARCHAR(10) NOT NULL\r\n,    Pieces INT NOT NULL\r\n,    Customer NVARCHAR(6) NOT NULL\r\n,    MaterialDocument NVARCHAR(10) NOT NULL\r\n,    SAPBatch NVARCHAR(10) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldMessages') AND type = 'U')\r\nCREATE TABLE dbo.EwaldMessages (\r\n    Batch NVARCHAR(20) NOT NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldScrapDocs') AND type = 'U')\r\nCREATE TABLE dbo.EwaldScrapDocs (\r\n    EwaldID NVARCHAR(10) NOT NULL\r\n,    ScrapDoc NVARCHAR(10) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldWaste') AND type = 'U')\r\nCREATE TABLE dbo.EwaldWaste (\r\n    EwaldID NVARCHAR(10) NOT NULL\r\n,    Drum NVARCHAR(10) NOT NULL\r\n,    WasteID NVARCHAR(4) NOT NULL\r\n,    Pieces INT NOT NULL\r\n,    BomAdjustment INT NOT NULL\r\n,    Weight NVARCHAR(50) NOT NULL\r\n,    ScrapDoc NVARCHAR(10) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Extrusion') AND type = 'U')\r\nCREATE TABLE dbo.Extrusion (\r\n    ExtBatch NVARCHAR(11) NOT NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    Meters FLOAT NOT NULL\r\n,    Operator NVARCHAR(50) NOT NULL\r\n,    CreationDate NVARCHAR(10) NOT NULL\r\n,    CreationTime NVARCHAR(5) NOT NULL\r\n,    StartDate NVARCHAR(10) NOT NULL\r\n,    StartTime NVARCHAR(5) NOT NULL\r\n,    StopTime NVARCHAR(5) NOT NULL\r\n,    MaterialDocument NVARCHAR(10) NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n,    StopDate DATETIME NULL\r\n,    Preforms INT NULL\r\n,    ProductionNumber NVARCHAR(12) NULL\r\n,    Inspector NVARCHAR(50) NULL\r\n,    Setter NVARCHAR(50) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionMessages') AND type = 'U')\r\nCREATE TABLE dbo.ExtrusionMessages (\r\n    Batch NVARCHAR(10) NOT NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionTrace') AND type = 'U')\r\nCREATE TABLE dbo.ExtrusionTrace (\r\n    ExtBatch NVARCHAR(10) NOT NULL\r\n,    MixCode NVARCHAR(18) NOT NULL\r\n,    MixBatch NVARCHAR(10) NOT NULL\r\n,    TubNo INT NULL\r\n,    ConditionTime NVARCHAR(5) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionWaste') AND type = 'U')\r\nCREATE TABLE dbo.ExtrusionWaste (\r\n    ExtBatch NVARCHAR(10) NOT NULL\r\n,    Operator NVARCHAR(50) NOT NULL\r\n,    Reason NVARCHAR(4) NOT NULL\r\n,    ScrWeight NVARCHAR(50) NOT NULL\r\n,    KGpM NVARCHAR(50) NOT NULL\r\n,    SapScrap NVARCHAR(50) NOT NULL\r\n,    Allowance NVARCHAR(50) NOT NULL\r\n,    Component NVARCHAR(18) NOT NULL\r\n,    CompQty NVARCHAR(50) NOT NULL\r\n,    MatDoc NVARCHAR(10) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Firewall') AND type = 'U')\r\nCREATE TABLE dbo.Firewall (\r\n    Material NVARCHAR(18) NOT NULL\r\n,    SAPBatch NVARCHAR(10) NOT NULL\r\n,    FailedQty INT NOT NULL\r\n,    ReasonCode NVARCHAR(4) NOT NULL\r\n,    MatDoc NVARCHAR(10) NOT NULL\r\n,    ErrorMessage NVARCHAR(MAX) NOT NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.FirewallMessages') AND type = 'U')\r\nCREATE TABLE dbo.FirewallMessages (\r\n    SAPBatch NVARCHAR(10) NOT NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Messages') AND type = 'U')\r\nCREATE TABLE dbo.Messages (\r\n    Batch NVARCHAR(20) NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Mixing') AND type = 'U')\r\nCREATE TABLE dbo.Mixing (\r\n    MixingID NVARCHAR(10) NOT NULL\r\n,    MixCode NVARCHAR(18) NOT NULL\r\n,    TotalWeight NVARCHAR(50) NULL\r\n,    Shift NVARCHAR(50) NOT NULL\r\n,    Operator NVARCHAR(50) NOT NULL\r\n,    SupplierBatch NVARCHAR(20) NOT NULL\r\n,    BatchTub NVARCHAR(5) NOT NULL\r\n,    CreationDate NVARCHAR(50) NOT NULL\r\n,    CreationTime NVARCHAR(50) NOT NULL\r\n,    Comment NVARCHAR(MAX) NULL\r\n,    CreationDateParsed DATETIME NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingMatDocs') AND type = 'U')\r\nCREATE TABLE dbo.MixingMatDocs (\r\n    MixingBatch NVARCHAR(10) NOT NULL\r\n,    MatDoc NVARCHAR(10) NOT NULL\r\n,    ReversalDoc NVARCHAR(10) NULL\r\n,    TubWeight FLOAT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingMessages') AND type = 'U')\r\nCREATE TABLE dbo.MixingMessages (\r\n    Batch NVARCHAR(10) NOT NULL\r\n,    Message NVARCHAR(MAX) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingWaste') AND type = 'U')\r\nCREATE TABLE dbo.MixingWaste (\r\n    MixingID NVARCHAR(10) NULL\r\n,    Material NVARCHAR(18) NOT NULL\r\n,    Weight FLOAT NOT NULL\r\n,    Reason NVARCHAR(4) NOT NULL\r\n,    Operator NVARCHAR(10) NOT NULL\r\n,    Shift NVARCHAR(10) NOT NULL\r\n,    SupplierBatch NVARCHAR(50) NULL\r\n,    SupplierTub NVARCHAR(10) NULL\r\n,    MaterialDocument NVARCHAR(10) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.test') AND type = 'U')\r\nCREATE TABLE dbo.test (\r\n    EntryType NVARCHAR(50) NULL\r\n,    CustomerCode NVARCHAR(50) NULL\r\n,    Material NVARCHAR(50) NULL\r\n,    Length NVARCHAR(50) NULL\r\n,    SAPLabel NVARCHAR(50) NULL\r\n,    MaterialDoc NVARCHAR(50) NULL\r\n,    Scrap NVARCHAR(50) NULL\r\n,    DateSubmitted NVARCHAR(50) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Trace') AND type = 'U')\r\nCREATE TABLE dbo.Trace (\r\n    Batch NVARCHAR(20) NOT NULL\r\n,    PreviousBatch NVARCHAR(20) NOT NULL\r\n,    Component NVARCHAR(18) NOT NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Waste') AND type = 'U')\r\nCREATE TABLE dbo.Waste (\r\n    Batch NVARCHAR(20) NOT NULL\r\n,    Reason NVARCHAR(4) NOT NULL\r\n,    Length FLOAT NOT NULL\r\n,    Weight NVARCHAR(50) NULL\r\n\r\n)");

    await knex.raw("IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ScrapReasons') AND type = 'U')\r\nCREATE TABLE dbo.ScrapReasons (\r\n    ReasonCode INT NOT NULL\r\n,    ReasonDescription NVARCHAR(MAX) NULL\r\n\r\n)");
};

/** @param {import('knex').Knex} knex */
exports.down = async function (knex) {


    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.archive') AND type = 'U') DROP TABLE dbo.archive");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Batches') AND type = 'U') DROP TABLE dbo.Batches");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Coils') AND type = 'U') DROP TABLE dbo.Coils");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Convo') AND type = 'U') DROP TABLE dbo.Convo");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoMessages') AND type = 'U') DROP TABLE dbo.ConvoMessages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoTrace') AND type = 'U') DROP TABLE dbo.ConvoTrace");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ConvoWaste') AND type = 'U') DROP TABLE dbo.ConvoWaste");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Emails') AND type = 'U') DROP TABLE dbo.Emails");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Ewald') AND type = 'U') DROP TABLE dbo.Ewald");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldBoxes') AND type = 'U') DROP TABLE dbo.EwaldBoxes");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldMessages') AND type = 'U') DROP TABLE dbo.EwaldMessages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldScrapDocs') AND type = 'U') DROP TABLE dbo.EwaldScrapDocs");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.EwaldWaste') AND type = 'U') DROP TABLE dbo.EwaldWaste");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Extrusion') AND type = 'U') DROP TABLE dbo.Extrusion");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionMessages') AND type = 'U') DROP TABLE dbo.ExtrusionMessages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionTrace') AND type = 'U') DROP TABLE dbo.ExtrusionTrace");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ExtrusionWaste') AND type = 'U') DROP TABLE dbo.ExtrusionWaste");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Firewall') AND type = 'U') DROP TABLE dbo.Firewall");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.FirewallMessages') AND type = 'U') DROP TABLE dbo.FirewallMessages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Messages') AND type = 'U') DROP TABLE dbo.Messages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Mixing') AND type = 'U') DROP TABLE dbo.Mixing");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingMatDocs') AND type = 'U') DROP TABLE dbo.MixingMatDocs");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingMessages') AND type = 'U') DROP TABLE dbo.MixingMessages");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MixingWaste') AND type = 'U') DROP TABLE dbo.MixingWaste");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.test') AND type = 'U') DROP TABLE dbo.test");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Trace') AND type = 'U') DROP TABLE dbo.Trace");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.Waste') AND type = 'U') DROP TABLE dbo.Waste");
    await knex.raw("IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.ScrapReasons') AND type = 'U') DROP TABLE dbo.ScrapReasons");

};
